version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "e2e-tracing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5bzzz9oopyf0"
s3_prefix = "e2e-tracing"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

